package anhnd.entity;
// Generated Feb 2, 2021 8:57:17 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Registrations generated by hbm2java
 */
public class Registrations  implements java.io.Serializable {


     private String registrationId;
     private String fullname;
     private String phone;
     private String email;
     private String address;
     private Integer age;
     private Boolean gender;
     private Integer numberOfMember;
     private Integer numberOfChildren;
     private Integer numberOfAdults;

    public Registrations() {
    }

	
    public Registrations(String registrationId) {
        this.registrationId = registrationId;
    }
    public Registrations(String registrationId, String fullname, String phone, String email, String address, Integer age, Boolean gender, Integer numberOfMember, Integer numberOfChildren, Integer numberOfAdults) {
       this.registrationId = registrationId;
       this.fullname = fullname;
       this.phone = phone;
       this.email = email;
       this.address = address;
       this.age = age;
       this.gender = gender;
       this.numberOfMember = numberOfMember;
       this.numberOfChildren = numberOfChildren;
       this.numberOfAdults = numberOfAdults;
    }
   
    public String getRegistrationId() {
        return this.registrationId;
    }
    
    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public Boolean getGender() {
        return this.gender;
    }
    
    public void setGender(Boolean gender) {
        this.gender = gender;
    }
    public Integer getNumberOfMember() {
        return this.numberOfMember;
    }
    
    public void setNumberOfMember(Integer numberOfMember) {
        this.numberOfMember = numberOfMember;
    }
    public Integer getNumberOfChildren() {
        return this.numberOfChildren;
    }
    
    public void setNumberOfChildren(Integer numberOfChildren) {
        this.numberOfChildren = numberOfChildren;
    }
    public Integer getNumberOfAdults() {
        return this.numberOfAdults;
    }
    
    public void setNumberOfAdults(Integer numberOfAdults) {
        this.numberOfAdults = numberOfAdults;
    }




}


